[lbservers]
178.62.52.142 name=partup-loadbalancer-london1-01

[appservers-staging]
178.62.48.222 name=partup-staging-london1-01

[appservers-acceptance]
178.62.29.238 name=partup-acceptance-london1-01
178.62.82.115 name=partup-acceptance-london1-02

[appservers-production]
178.62.88.196 name=partup-production-london1-04
46.101.10.191 name=partup-production-london1-05
178.62.125.185 name=partup-production-london1-06
46.101.1.145 name=partup-production-london1-07

[appservers-all:children]
appservers-staging
appservers-acceptance
appservers-production

[loadbalancer:children]
lbservers

[loadbalancer:vars]
server_environment_name=loadbalancer
