[lbservers]
178.62.52.142 name=partup-loadbalancer-london1-01

[appservers-staging]
178.62.48.222 name=partup-staging-london1-01

[appservers-acceptance]
178.62.29.238 name=partup-acceptance-london1-01
178.62.82.115 name=partup-acceptance-london1-02

[appservers-production]
46.101.51.124 name=partup-production-london1-01
178.62.67.36 name=partup-production-london1-02
178.62.109.142 name=partup-production-london1-03

[appservers-all:children]
appservers-staging
appservers-acceptance
appservers-production

[loadbalancer:children]
lbservers

[loadbalancer:vars]
server_environment_name=loadbalancer
