---
- name: newrelic | add apt repository
  lineinfile: dest=/etc/apt/sources.list.d/newrelic.list line="deb http://apt.newrelic.com/debian/ newrelic non-free" state=present create=true insertafter=EOF
  tags: newrelic

- name: newrelic | trust GPG key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present
  tags: newrelic

- name: newrelic | install
  apt: package=newrelic-sysmond state=latest update_cache=yes
  tags: newrelic

- name: newrelic | set license key
  shell: nrsysmond-config --set license_key={{ common.newrelic.license_key }}
  tags: newrelic

- name: newrelic | add docker group
  group: name=docker state=present
  tags: newrelic

- name: newrelic | add newrelic user to docker group
  user: name=newrelic groups=docker append=yes
  tags: newrelic

- name: newrelic | start daemon
  service: name=newrelic-sysmond state=restarted
  tags: newrelic
