phraseapp:
  project_id: 44c4823aea4c479fd3d5f3feaffecd04
  file_format: simple_json
  push:
    sources:
    - file: ./app/i18n/phraseapp.<locale_code>.i18n.json
  pull:
    targets:
    - file: ./app/i18n/phraseapp.<locale_code>.i18n.json
