---
- hosts: appservers-staging
  gather_facts: yes
  remote_user: root

- hosts: appservers-acceptance
  gather_facts: yes
  remote_user: root

- hosts: appservers-production
  gather_facts: yes
  remote_user: root

- hosts: lbservers
  gather_facts: yes
  remote_user: root
  sudo: yes
  roles:
    - loadbalancer
  vars_prompt:
    - name: deploy_environment
      prompt: Which environment do you want to provision the loadbalancer for (all|staging|acceptance|production)?
      private: no
    - name: deploy_mode
      prompt: Which mode do you want to provision the loadbalancer in (live|modulus|maintenance)?
      default: live
      private: no
