---
- name: ansible | add ppa
  apt_repository: repo='ppa:ansible/ansible' state=present
  tags: ansible

- name: ansible | install
  apt: package=ansible update-cache=yes state=latest
  tags: ansible

- name: ansible | add ssh-key
  template: src=~/.ssh/partup-server dest=/var/lib/jenkins/.ssh/partup-server mode=0600 owner=jenkins group=docker
  tags: ansible
