---
- name: aws | install python-pip
  apt: package=python-pip state=latest update_cache=yes
  tags: aws

- name: aws | install awscli
  pip: name=awscli state=latest
  tags: aws

- name: aws | create configuration directory
  file: path=/var/lib/jenkins/.aws state=directory owner=jenkins
  tags: aws

- name: aws | add configuration
  template: src=aws-config.tpl dest=/var/lib/jenkins/.aws/config
  tags: aws
