---
- name: jenkins | trust key
  shell: wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
  tags: jenkins

- name: jenkins | add package source
  shell: sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
  tags: jenkins

- name: jenkins | install
  apt: name=jenkins state=latest update_cache=yes
  tags: jenkins

- name: jenkins | ensure .ssh directory exists
  shell: mkdir -p /var/lib/jenkins/.ssh
  sudo_user: jenkins
  tags: jenkins

- name: jenkins | provision id_rsa
  template: src=ssl/jenkins dest=/var/lib/jenkins/.ssh/id_rsa mode=0600 owner=jenkins
  sudo_user: jenkins
  tags: jenkins

- name: jenkins | provision id_rsa.pub
  template: src=ssl/jenkins.pub dest=/var/lib/jenkins/.ssh/id_rsa.pub mode=0600 owner=jenkins
  sudo_user: jenkins
  tags: jenkins

- name: jenkins | add jenkins user to www-data group
  user: name=jenkins group=www-data append=yes
  tags: jenkins

- name: jenkins | add jenkins user to docker group
  user: name=jenkins group=docker append=yes
  tags: jenkins
