---
- name: nginx | install
  apt: package=nginx state=latest
  tags: nginx

- name: nginx | start
  service: name=nginx state=started
  tags: nginx

- name: nginx | add firewall exceptions
  shell: |-
      ufw allow 80
      ufw allow 443
  tags: nginx

- name: nginx | remove default vhost
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: nginx

- name: nginx | add jenkins vhost
  template: src=nginx-vhost-jenkins.tpl dest=/etc/nginx/sites-available/jenkins
  notify: nginx | reload
  tags: nginx

- name: nginx | enable jenkins vhost
  file: src=/etc/nginx/sites-available/jenkins dest=/etc/nginx/sites-enabled/jenkins state=link
  notify: nginx | reload
  tags: nginx

- name: nginx | ensure /var/www exists
  file: path=/var/www state=directory owner=www-data group=www-data mode=774
  tags: nginx
