---
- hosts: appservers
  gather_facts: no
  tasks:
   - name: backup | variable - timestamp
     local_action: shell /bin/date +"%Y-%m-%d-%H%M%S"
     register: timestamp
     run_once: true

   - name: backup | create directory
     local_action: shell mkdir -p ../backups/{{ app.env.NODE_ENV }}/{{ timestamp.stdout }}/{mongodb,s3-bucket}
     run_once: true

   - name: backup | database
     local_action: shell mongodump -h {{ database.host }} -u {{ database.user }} -p {{ database.password }}  --db {{ database.name }} -o ../backups/{{ app.env.NODE_ENV }}/{{ timestamp.stdout }}/mongodb
     run_once: true

   - name: backup | storage
     local_action: shell aws s3 sync s3://{{ app.env.AWS_BUCKET_NAME }} ../backups/{{ app.env.NODE_ENV }}/{{ timestamp.stdout }}/s3-bucket
     run_once: true
