---
- name: docker | apt update
  apt: update_cache=yes
  tags: docker

- name: docker | install
  shell: wget -qO- https://get.docker.com/ | sh
  args:
    creates: /usr/bin/docker
  tags: docker

- name: docker | install python setuptools
  apt: package=python-setuptools state=latest
  tags: docker

- name: docker | install pip
  shell: easy_install -U pip
  tags: docker

- name: docker | install docker-py
  pip: name=docker-py version=1.2.3
  tags: docker

- name: docker | start logspout container
  docker:
    command: "{{ docker.syslog }}"
    env:
      SYSLOG_HOSTNAME: "{{ ansible_nodename }}"
    name: logspout
    image: "gliderlabs/logspout"
    username: "{{ docker.registry.username }}"
    email: "{{ docker.registry.email }}"
    password: "{{ docker.registry.password }}"
    state: reloaded
    restart_policy: always
    pull: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  tags: docker
