---
- name: docker | apt update
  apt: update_cache=yes
  tags: docker

- name: docker | install
  shell: wget -qO- https://get.docker.com/ | sh
  args:
    creates: /usr/bin/docker
  tags: docker

- name: docker | install python setuptools
  apt: package=python-setuptools state=latest
  tags: docker

- name: docker | install pip
  shell: easy_install -U pip
  tags: docker

- name: docker | install docker-py
  pip: name=docker-py version=1.2.3
  tags: docker
