---
- hosts: appservers
  gather_facts: no
  tasks:
   - name: datadump | create directory
     local_action: shell mkdir -p ../backups/{{ app.env.NODE_ENV }}/datadump
     run_once: true

   - name: datadump | dump database
     local_action: shell mongodump -h {{ database.host }} -u {{ database.user }} -p {{ database.password }} --db {{ database.name }} -o ../backups/{{ app.env.NODE_ENV }}/datadump
     run_once: true

   - name: datadump | remove metadata
     local_action: shell rm -rf ../backups/{{ app.env.NODE_ENV }}/datadump/{{ database.name }}/*.json
     run_once: true

   - name: datadump | unpack bson files to json
     local_action: shell for f in ../backups/{{ app.env.NODE_ENV }}/datadump/{{ database.name }}/*.bson; do bsondump "$f" > "$f.json"; done
     run_once: true

   - name: datadump | remove all bson files
     local_action: shell rm -rf ../backups/{{ app.env.NODE_ENV }}/datadump/{{ database.name }}/*.bson
     run_once: true

   - name: datadump | remove all tokens
     local_action: shell devops/commands/scripts/datadump.sh ../backups/{{ app.env.NODE_ENV }}/datadump/{{ database.name }}
     run_once: true
